### PR TITLE
Update demo branch with dev changes

### PR DESCRIPTION
**Pull request by Toby222**
I really did my best.
Check on https://spaceship-incremental-j2s35gppt-toby222.vercel.app/ whether everything is correct before merging.

### CODE REVIEW

**Comment by UnwieldyKhan** [comment]
Is there a reason to use `overflow-y: scroll` instead of `auto`?

**Comment by Toby222** [comment]
Scroll makes the scroll bar be there all the time, meaning the page size won't change when you switch between tabs of different heights

**Comment by UnwieldyKhan** [comment]
Yeah, but scroll keeps the scrollbar even when the screen is big enough.

**Comment by Toby222** [comment]
> Yeah, but scroll keeps the scrollbar even when the screen is big enough.

The only ways I can see that would avoid that would be a media query that disables the scroll bar for screens above a certain size (1409px, seems like?), which would require hard-coding that size.
Or using JS to check if the window is tall enough, with a corresponding onresize event handler, which ig I'll try now.

**Comment by UnwieldyKhan** [comment]
I was talking about the `auto` value of `overflow` which automatically does that for you ([mdn](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow#:~:text=print%20overflowing%20content.-,auto,new%20block%20formatting%20context.%20Desktop%20browsers%20provide%20scrollbars%20if%20content%20overflows.,-overlay)).

**Comment by Toby222** [comment]
> I was talking about the `auto` value of `overflow` which automatically does that for you ([mdn](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow#:~:text=print%20overflowing%20content.-,auto,new%20block%20formatting%20context.%20Desktop%20browsers%20provide%20scrollbars%20if%20content%20overflows.,-overlay)).

`auto` works when the content overflows. I prefer to keep the scroll bar because page height changes when switching tabs, causing the page to overflow or stop overflowing and the scroll bar to appear and disappear.
This causes a layout shift that's uglier to look at than just a temporarily unused scroll bar, imho.
Obviously the problem is a bit different on screens large enough to fit the largest tab without scrolling.

**Pull request merged**
